const generator = require('../src/core/manifest-generator');
const childProcess = require('child_process');
const fs = require('fs');
const assert = require('assert');
const path = require('path');

// Mock child_process.execSync
const originalExecSync = childProcess.execSync;
let mockExecSyncResponse = '';
childProcess.execSync = (command, options) => {
    if (command.includes('gh --version')) {
        return 'gh version 2.40.0';
    }
    console.log(`[Mock Exec] ${command}`);
    return mockExecSyncResponse;
};

// Mock fs
const originalExistsSync = fs.existsSync;
const originalReadFileSync = fs.readFileSync;

// Test Suite
async function runTests() {
    console.log('🧪 Testing Manifest Generator...');

    // Setup FS mocks
    const mockRepoPath = '/mock/repo';

    fs.existsSync = (p) => {
        if (p.includes('package.json')) return true;
        if (p.includes('README.md')) return true;
        return false;
    };

    fs.readFileSync = (p) => {
        if (p.includes('package.json')) {
            return JSON.stringify({
                name: 'test-project',
                scripts: { test: 'jest', build: 'tsc' }
            });
        }
        return '';
    };

    try {
        // Test 1: Generate from Repo
        console.log('Test 1: Generate from Repo...');

        mockExecSyncResponse = `
name: test-project
description: Generated by Copilot
dependencies:
  npm:
    - jest
    - typescript
setupSteps:
  - name: Install
    command: npm install
  - name: Build
    command: npm run build
`;

        const yaml = await generator.generateFromRepo(mockRepoPath);

        assert.ok(yaml.includes('name: test-project'));
        assert.ok(yaml.includes('npm install'));
        console.log('  ✓ YAML generated correctly');

        // Test 2: Error Handling
        console.log('Test 2: Copilot Error...');
        childProcess.execSync = (cmd) => {
            if (cmd.includes('gh --version')) return 'ver';
            throw new Error('Copilot failed');
        };

        try {
            await generator.generateFromRepo(mockRepoPath);
            assert.fail('Should have thrown error');
        } catch (e) {
            assert.ok(e.message.includes('Copilot failed'));
            console.log('  ✓ Error handled correctly');
        }

        console.log('\n✅ All manifest generator tests passed!');
    } catch (error) {
        console.error('\n❌ Tests failed:', error);
        process.exit(1);
    } finally {
        // Restore mocks
        childProcess.execSync = originalExecSync;
        fs.existsSync = originalExistsSync;
        fs.readFileSync = originalReadFileSync;
    }
}

runTests();
