const generator = require('../src/core/manifest-generator');
const childProcess = require('child_process');
const fs = require('fs');

jest.mock('child_process');
jest.mock('fs');

describe('Manifest Generator Tests', () => {

    beforeEach(() => {
        childProcess.execSync.mockReset();
        // Setup default mock response for gh version check
        childProcess.execSync.mockImplementation((cmd) => {
            if (cmd.includes('gh --version')) return 'gh version 2.40.0';
            return '';
        });

        fs.existsSync.mockReset();
        fs.readFileSync.mockReset();
    });

    test('Generate from Repo', async () => {
        const mockRepoPath = '/mock/repo';

        fs.existsSync.mockImplementation((p) => {
            if (p.includes('package.json')) return true;
            if (p.includes('README.md')) return true;
            return false;
        });

        fs.readFileSync.mockImplementation((p) => {
            if (p.includes('package.json')) {
                return JSON.stringify({
                    name: 'test-project',
                    scripts: { test: 'jest', build: 'tsc' }
                });
            }
            return '';
        });

        const mockResponse = `
name: test-project
description: Generated by Copilot
dependencies:
  npm:
    - jest
    - typescript
setupSteps:
  - name: Install
    command: npm install
  - name: Build
    command: npm run build
`;
        childProcess.execSync.mockReturnValue(mockResponse);

        const yaml = await generator.generateFromRepo(mockRepoPath);

        expect(yaml).toContain('name: test-project');
        expect(yaml).toContain('npm install');
    });

    test('Copilot Error Handling', async () => {
        const mockRepoPath = '/mock/repo';
        childProcess.execSync.mockImplementation((cmd) => {
            if (cmd.includes('gh --version')) return 'ver';
            throw new Error('Copilot failed');
        });

        await expect(generator.generateFromRepo(mockRepoPath))
            .rejects.toThrow('Copilot failed');
    });

});
