name: demo-app
description: Demo Express App
dependencies:
  npm:
    - express
    - cors
  system: []
  python: []
environment:
  required:
    - PORT
setup_steps:
  - name: Install Dependencies
    command: npm install
  - name: Build
    command: npm run build
verification:
  checks:
    - name: Verify URL
      type: http
      url: http://localhost:3000
      priority: P0